# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowportret', '0005_auto_20160530_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='../tmp_img/'),
        ),
    ]
