# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import wowportret.models


class Migration(migrations.Migration):

    dependencies = [
        ('wowportret', '0007_auto_20160530_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=wowportret.models.content_file_name),
        ),
    ]
