# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 22:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations
import galleryserve.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('wowportret', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=galleryserve.thumbs.ImageWithThumbsField(blank=True, upload_to='galleryserve/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
