# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 22:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowportret', '0013_auto_20160629_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mini_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
