# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content',
            field=models.CharField(default='swag desc', max_length=200),
            preserve_default=False,
        ),
    ]
