# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0002_gallery_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='height',
            field=models.IntegerField(blank=True, default=300, help_text='Height images should be resized to in pixels'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='width',
            field=models.IntegerField(blank=True, default=400, help_text='Width images should be resized to in pixels'),
        ),
    ]
