# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0005_auto_20160604_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
    ]
