# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0006_gallery_has_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
