# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0008_auto_20160605_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='galleryserve/images'),
        ),
    ]
