# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 17:23
from __future__ import unicode_literals

from django.db import migrations
import galleryserve.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0009_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('id',), 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=galleryserve.thumbs.ImageWithThumbsField(blank=True, upload_to='galleryserve/images'),
        ),
    ]
