# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0013_auto_20160605_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, help_text='Цена'),
        ),
    ]
