# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0015_auto_20160606_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='has_child',
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_baget',
            field=models.BooleanField(default=False, help_text='Is it baguette gallery'),
        ),
    ]
