# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0017_gallery_has_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=models.CharField(blank=True, help_text='Mini description of gallery', max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(help_text='Title of gallery', max_length=200),
        ),
    ]
