# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0018_auto_20160630_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('title',), 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('sort', 'title')},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Mini description of gallery'),
        ),
    ]
