# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryserve', '0021_auto_20160711_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-title',)},
        ),
    ]
